export default {
	tableStyle: {display: "inline-block"},
	fontSizeStyle: {fontSize: 12},
	formMaxWidth: {maxWidth: '90%'},
	formMargin: {margin: '0 auto'},
	componentMarginTop: { marginTop: 20},
	menuTopMargin: {marginTop: 40},
	formIconsTopMargin: {marginTop: 35},
	ageInputsStyle: {width: '80%'},
	sexSwitchesBlock: {maxWidth: 250},
	sexSwitchesRadioButton: { marginBottom: 16},
	sexSwitchesButtonsMarginTop: {marginTop: 40},
	formHeading: { textAlign: 'center'},
	resetButtonMargin: {margin: '0 auto'},
	resetButtonWidth: {display: 'block'},
	resetButtonDisplay: {width: 150},
	centerSelectableRow: {marginLeft: "20%", marginTop: 40 },
	centerSumbitButtonsRow: {marginLeft: '35%', marginTop: 40},
	raisedButtonFloatAndWidth: {float: 'right', width: 150, marginLeft: 5}
};